name: Node.js CI

on: [push, pull_request]

jobs:
  build:
    runs-on: ubuntu-22.04

    steps:
    - uses: actions/checkout@v3
    - name: Use Node.js 18
      uses: actions/setup-node@v3
      with:
        node-version: 18
    - run: npm ci
    - name: build
      run: npx webpack --mode=production
      env:
        PUBLIC_PATH: '/AncientBeast/'
    - name: Upload build artifact
      uses: actions/upload-artifact@v1
      with:
        name: deploy
        path: deploy
        
  codeanalysis:
    runs-on: ubuntu-22.04
    needs: build

    steps: 
    - name: Install Dependencies
      run: npm install
    - name: Static Code Analysis (ESLint)
      run: npm run lint

    - name: Archive ESLint Report
      uses: actions/upload-artifact@v2
      with:
        name: eslint-report
        path: eslint-report.log
        
