name: Build and configure

on: [push, pull_request]

jobs:
    
  test:
    runs-on: ubuntu-22.04


    steps:
    - name: Checkout code
      uses: actions/checkout@v2  
    
    - name: Use Node.js 18
      uses: actions/setup-node@v2  
      with:
        node-version: 18

    - name: Install dependencies
      run: npm ci

    - name: Lint code
      run: npm run lint  

    - name: Build for testing
      run: npm run build:dev 

    - name: Run tests
      run: npm test

    - name: Set code coverage commit status
      run: npx set-gh-status
      env:
         GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
      
